Authentication Microverse - Code Review
kevcap/members-only pull request #2
Opened 2020-07-28 15:07 UTC by kevincappuccino

# Project complete with:
- devise ruby gem
- authentication of users
- relation between posts and users
- validation of posts
- non-users restrictions

2020-07-28 18:28 UTC, wathigo requested changes
### Changes Required.
Great work guys :clap: 
There are still issues that need to be addressed before approving this project.

**REQUIRED**
* There is an error in an attempt to sign up for the application.
![Screenshot from 2020-07-28 21-24-55](https://user-images.githubusercontent.com/44072711/88705971-e46d2580-d118-11ea-9d5d-f7779cd0f38c.png)
_**Hint**: Check if you have configured devise to accept username as an extra parameter._

**After working on the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo.**

2020-07-28 18:28 UTC, wathigo commented on config/routes.rb
> +  resources :posts
**REQUIRED**
* It creates the application routes using `resources :posts, only: [:new, :create, :index]` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

2020-07-28 18:28 UTC, wathigo commented on config/routes.rb
> +  resources :users, only: [:show]
**REQUIRED**
* This is totally unnecessary since we don't have users controller.
`devise_for :users` is enough in this case.

2020-07-28 18:28 UTC, wathigo commented on app/views/posts/index.html.erb
> +    <h5 class="card-title"><%=post.title%></h5> <% if signed_in? %> <small class="text-muted">Author: <%= post.user.username %></small>
**REQUIRED** 
* [ ] There should be absolutely NO logic in views.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

2020-07-28 18:28 UTC, wathigo commented on app/views/posts/index.html.erb
> +    <% else %>
**REQUIRED**
* [ ] There should be absolutely NO logic in views.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

2020-07-28 18:28 UTC, wathigo commented on app/views/posts/new.html.erb
> +  <% if @post.errors.any? %>
* [ ] There should be absolutely NO logic in views.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

2020-07-28 18:28 UTC, wathigo commented on app/views/posts/show.html.erb
> +  <% if signed_in? %>
* [ ] There shoud be absolutely NO logic in views.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

2020-07-28 23:49 UTC, uche-inyama requested changes
## Changes required

Hi team :wave: 

There is a change you need to implement.

- [ ]  Signing up on your application still gives the error pointed to by the previous TSE.
Checking your user object in the console, there is no username as an attribute.

![Screenshot from 2020-07-29 00-36-54](https://user-images.githubusercontent.com/46329537/88740466-260bc980-d135-11ea-9574-1fe5b73b4719.png)

Please, make the update to the user model, then submit another form for a code review.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

2020-07-29 08:50 UTC, kevincappuccino commented
@uche-inyama could you check if at ```db/schema.rb```, at the users table, if is there a column  ```t.string "username"```? Because in our machines is working fine, and we're trying to figure it out.

2020-07-29 10:13 UTC, rOluochKe approved these changes
Hello Team
### You this right, well done :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-07-29 11:08 UTC, merged